// 人教版小学数学教材目录（轻量结构层）
// 这里不存放教材正文，只存放年级、册次、单元名，以及当前题库已经接入的知识点位置。

const p = (topicId, displayTitle, options = {}) => {
  const extra = typeof options === 'string' ? { objective: options } : options;
  return { topicId, displayTitle, ...extra };
};

export const PRIMARY_CURRICULUM = [
  {
    id: 'g1-upper',
    stage: '小学',
    grade: 1,
    volume: 'upper',
    volumeLabel: '上册',
    title: '一年级上册',
    units: [
      { unit: 1, title: '准备课', topics: [] },
      { unit: 2, title: '位置', topics: [p('position-basic', '上、下、前、后、左、右')] },
      { unit: 3, title: '1-5 的认识和加减法', topics: [p('add-sub', '1-5 的加减法', { scope: { id: 'within-5' } })] },
      { unit: 4, title: '认识图形（一）', topics: [p('shape-basic', '认识立体图形', { scope: { id: 'solid' } })] },
      { unit: 5, title: '6-10 的认识和加减法', topics: [p('add-sub', '10 以内加减法', { scope: { id: 'within-10' } })] },
      { unit: 6, title: '11-20 各数的认识', topics: [] },
      { unit: 7, title: '认识钟表', topics: [p('clock-basic', '认识整时和半时', { scope: { id: 'whole-half' } })] },
      { unit: 8, title: '20 以内的进位加法', topics: [p('add-sub', '20 以内进位加法', { scope: { id: 'plus-within-20-carry' } })] },
      { unit: 9, title: '总复习', topics: [] },
    ],
  },
  {
    id: 'g1-lower',
    stage: '小学',
    grade: 1,
    volume: 'lower',
    volumeLabel: '下册',
    title: '一年级下册',
    units: [
      { unit: 1, title: '认识图形（二）', topics: [p('shape-basic', '认识平面图形', { scope: { id: 'plane' } })] },
      { unit: 2, title: '20 以内的退位减法', topics: [p('add-sub', '20 以内退位减法', { scope: { id: 'minus-within-20-borrow' } })] },
      { unit: 3, title: '分类与整理', topics: [p('classify-basic', '按标准分类和计数')] },
      { unit: 4, title: '100 以内数的认识', topics: [] },
      { unit: 5, title: '认识人民币', topics: [p('money-basic', '人民币的简单计算')] },
      { unit: 6, title: '100 以内的加法和减法（一）', topics: [p('add-sub', '100 以内加减法（一）', { scope: { id: 'within-100-basic' } })] },
      { unit: 7, title: '找规律', topics: [p('pattern-basic', '简单重复规律')] },
      { unit: 8, title: '总复习', topics: [] },
    ],
  },
  {
    id: 'g2-upper',
    stage: '小学',
    grade: 2,
    volume: 'upper',
    volumeLabel: '上册',
    title: '二年级上册',
    units: [
      { unit: 1, title: '长度单位', topics: [p('length-unit', '厘米和米')] },
      { unit: 2, title: '100 以内的加法和减法（二）', topics: [p('add-sub', '100 以内加减法（二）', { scope: { id: 'within-100-carry' } })] },
      { unit: 3, title: '角的初步认识', topics: [] },
      { unit: 4, title: '表内乘法（一）', topics: [p('mul-div', '表内乘法（一）', { scope: { id: 'table-mul-2-5' } })] },
      { unit: 5, title: '观察物体（一）', topics: [] },
      { unit: 6, title: '表内乘法（二）', topics: [p('mul-div', '表内乘法（二）', { scope: { id: 'table-mul-6-9' } })] },
      { unit: 7, title: '认识时间', topics: [p('clock-basic', '认识几时几分', { scope: { id: 'minutes' } })] },
      { unit: 8, title: '数学广角：搭配（一）', topics: [] },
      { unit: 9, title: '总复习', topics: [] },
    ],
  },
  {
    id: 'g2-lower',
    stage: '小学',
    grade: 2,
    volume: 'lower',
    volumeLabel: '下册',
    title: '二年级下册',
    units: [
      { unit: 1, title: '数据收集整理', topics: [p('data-basic', '读简单统计表')] },
      { unit: 2, title: '表内除法（一）', topics: [p('mul-div', '表内除法（一）', { scope: { id: 'table-div-2-5' } })] },
      { unit: 3, title: '图形的运动（一）', topics: [] },
      { unit: 4, title: '表内除法（二）', topics: [p('mul-div', '表内除法（二）', { scope: { id: 'table-div-6-9' } })] },
      { unit: 5, title: '混合运算', topics: [p('mul-div', '乘除混合运算', { scope: { id: 'table-mixed' } })] },
      { unit: 6, title: '有余数的除法', topics: [] },
      { unit: 7, title: '万以内数的认识', topics: [] },
      { unit: 8, title: '克和千克', topics: [] },
      { unit: 9, title: '数学广角：推理', topics: [] },
      { unit: 10, title: '总复习', topics: [] },
    ],
  },
  {
    id: 'g3-upper',
    stage: '小学',
    grade: 3,
    volume: 'upper',
    volumeLabel: '上册',
    title: '三年级上册',
    units: [
      { unit: 1, title: '时、分、秒', topics: [] },
      { unit: 2, title: '万以内的加法和减法（一）', topics: [p('add-sub', '万以内加减法（一）', { scope: { id: 'within-1000' } })] },
      { unit: 3, title: '测量', topics: [] },
      { unit: 4, title: '万以内的加法和减法（二）', topics: [p('add-sub', '万以内加减法（二）', { scope: { id: 'within-10000' } })] },
      { unit: 5, title: '倍的认识', topics: [] },
      { unit: 6, title: '多位数乘一位数', topics: [p('mul-div', '多位数乘一位数', { scope: { id: 'multi-one-digit' } })] },
      { unit: 7, title: '长方形和正方形', topics: [p('perimeter', '长方形和正方形的周长')] },
      { unit: 8, title: '分数的初步认识', topics: [p('fraction-visual', '分数的初步认识', { scope: { id: 'fraction-basic' } })] },
      { unit: 9, title: '数学广角：集合', topics: [] },
      { unit: 10, title: '总复习', topics: [] },
    ],
  },
  {
    id: 'g3-lower',
    stage: '小学',
    grade: 3,
    volume: 'lower',
    volumeLabel: '下册',
    title: '三年级下册',
    units: [
      { unit: 1, title: '位置与方向（一）', topics: [] },
      { unit: 2, title: '除数是一位数的除法', topics: [p('mul-div', '除数是一位数的除法', { scope: { id: 'divide-one-digit' } })] },
      { unit: 3, title: '复式统计表', topics: [] },
      { unit: 4, title: '两位数乘两位数', topics: [p('mul-div', '两位数乘两位数', { scope: { id: 'two-digit-two-digit' } })] },
      { unit: 5, title: '面积', topics: [p('area-rect', '长方形和正方形的面积')] },
      { unit: 6, title: '年、月、日', topics: [] },
      { unit: 7, title: '小数的初步认识', topics: [] },
      { unit: 8, title: '数学广角：搭配（二）', topics: [] },
      { unit: 9, title: '总复习', topics: [] },
    ],
  },
  {
    id: 'g4-upper',
    stage: '小学',
    grade: 4,
    volume: 'upper',
    volumeLabel: '上册',
    title: '四年级上册',
    units: [
      { unit: 1, title: '大数的认识', topics: [] },
      { unit: 2, title: '公顷和平方千米', topics: [] },
      { unit: 3, title: '角的度量', topics: [p('line-types', '线段、射线、直线'), p('angles', '角的度量与分类')] },
      { unit: 4, title: '三位数乘两位数', topics: [p('mul-div', '三位数乘两位数', { scope: { id: 'three-digit-two-digit' } })] },
      { unit: 5, title: '平行四边形和梯形', topics: [p('line-types', '线段、射线、直线')] },
      { unit: 6, title: '除数是两位数的除法', topics: [p('mul-div', '除数是两位数的除法', { scope: { id: 'divide-two-digit' } })] },
      { unit: 7, title: '条形统计图', topics: [] },
      { unit: 8, title: '数学广角：优化', topics: [] },
      { unit: 9, title: '总复习', topics: [] },
    ],
  },
  {
    id: 'g4-lower',
    stage: '小学',
    grade: 4,
    volume: 'lower',
    volumeLabel: '下册',
    title: '四年级下册',
    units: [
      { unit: 1, title: '四则运算', topics: [p('add-sub', '整数加减法'), p('mul-div', '乘法与除法')] },
      { unit: 2, title: '观察物体（二）', topics: [] },
      { unit: 3, title: '运算定律', topics: [] },
      { unit: 4, title: '小数的意义和性质', topics: [] },
      { unit: 5, title: '三角形', topics: [p('triangle-angle-sum', '三角形的内角和'), p('angles', '角的度量与分类')] },
      { unit: 6, title: '小数的加法和减法', topics: [] },
      { unit: 7, title: '图形的运动（二）', topics: [p('symmetry-axis', '轴对称图形的对称轴')] },
      { unit: 8, title: '平均数与条形统计图', topics: [] },
      { unit: 9, title: '数学广角：鸡兔同笼', topics: [] },
      { unit: 10, title: '总复习', topics: [] },
    ],
  },
  {
    id: 'g5-upper',
    stage: '小学',
    grade: 5,
    volume: 'upper',
    volumeLabel: '上册',
    title: '五年级上册',
    units: [
      { unit: 1, title: '小数乘法', topics: [] },
      { unit: 2, title: '位置', topics: [] },
      { unit: 3, title: '小数除法', topics: [] },
      { unit: 4, title: '可能性', topics: [p('probability-basic', '简单事件的概率')] },
      { unit: 5, title: '简易方程', topics: [] },
      { unit: 6, title: '多边形的面积', topics: [p('area-rect', '长方形和正方形的面积')] },
      { unit: 7, title: '数学广角：植树问题', topics: [] },
      { unit: 8, title: '总复习', topics: [] },
    ],
  },
  {
    id: 'g5-lower',
    stage: '小学',
    grade: 5,
    volume: 'lower',
    volumeLabel: '下册',
    title: '五年级下册',
    units: [
      { unit: 1, title: '观察物体（三）', topics: [] },
      { unit: 2, title: '因数与倍数', topics: [] },
      { unit: 3, title: '长方体和正方体', topics: [] },
      { unit: 4, title: '分数的意义和性质', topics: [p('fraction-visual', '分数的比较', { scope: { id: 'fraction-compare' } })] },
      { unit: 5, title: '图形的运动（三）', topics: [p('symmetry-axis', '轴对称图形的对称轴')] },
      { unit: 6, title: '分数的加法和减法', topics: [p('fraction-visual', '分数的加减', { scope: { id: 'fraction-add-sub' } })] },
      { unit: 7, title: '折线统计图', topics: [] },
      { unit: 8, title: '数学广角：找次品', topics: [] },
      { unit: 9, title: '总复习', topics: [] },
    ],
  },
  {
    id: 'g6-upper',
    stage: '小学',
    grade: 6,
    volume: 'upper',
    volumeLabel: '上册',
    title: '六年级上册',
    units: [
      { unit: 1, title: '分数乘法', topics: [] },
      { unit: 2, title: '位置与方向（二）', topics: [] },
      { unit: 3, title: '分数除法', topics: [] },
      { unit: 4, title: '比', topics: [p('ratio-scale', '比例尺与按比例缩放')] },
      { unit: 5, title: '圆', topics: [p('circle-measure', '圆的面积与周长'), p('sector-area', '扇形的面积')] },
      { unit: 6, title: '百分数（一）', topics: [] },
      { unit: 7, title: '扇形统计图', topics: [] },
      { unit: 8, title: '数学广角：数与形', topics: [] },
      { unit: 9, title: '总复习', topics: [] },
    ],
  },
  {
    id: 'g6-lower',
    stage: '小学',
    grade: 6,
    volume: 'lower',
    volumeLabel: '下册',
    title: '六年级下册',
    units: [
      { unit: 1, title: '负数', topics: [] },
      { unit: 2, title: '百分数（二）', topics: [] },
      { unit: 3, title: '圆柱与圆锥', topics: [] },
      { unit: 4, title: '比例', topics: [p('ratio-scale', '比例尺与按比例缩放')] },
      { unit: 5, title: '数学广角：鸽巢问题', topics: [] },
      { unit: 6, title: '整理和复习', topics: [] },
    ],
  },
];
